// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CanalModelProtocol.proto

package com.alibaba.otter.canal.instance.manager.protocol;

public final class CanalModelPacket {
  private CanalModelPacket() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code CanalStatusMessage}
   */
  public enum CanalStatusMessage
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>START = 0;</code>
     */
    START(0),
    /**
     * <code>STOP = 1;</code>
     */
    STOP(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>START = 0;</code>
     */
    public static final int START_VALUE = 0;
    /**
     * <code>STOP = 1;</code>
     */
    public static final int STOP_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static CanalStatusMessage valueOf(int value) {
      return forNumber(value);
    }

    public static CanalStatusMessage forNumber(int value) {
      switch (value) {
        case 0: return START;
        case 1: return STOP;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<CanalStatusMessage>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        CanalStatusMessage> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<CanalStatusMessage>() {
            public CanalStatusMessage findValueByNumber(int number) {
              return CanalStatusMessage.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.alibaba.otter.canal.instance.manager.protocol.CanalModelPacket.getDescriptor().getEnumTypes().get(0);
    }

    private static final CanalStatusMessage[] VALUES = values();

    public static CanalStatusMessage valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private CanalStatusMessage(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:CanalStatusMessage)
  }

  public interface CanalModelMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CanalModelMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int64 id = 1;</code>
     */
    long getId();

    /**
     * <code>optional string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>optional string desc = 3;</code>
     */
    java.lang.String getDesc();
    /**
     * <code>optional string desc = 3;</code>
     */
    com.google.protobuf.ByteString
        getDescBytes();

    /**
     * <code>optional .CanalStatusMessage status = 4;</code>
     */
    int getStatusValue();
    /**
     * <code>optional .CanalStatusMessage status = 4;</code>
     */
    com.alibaba.otter.canal.instance.manager.protocol.CanalModelPacket.CanalStatusMessage getStatus();

    /**
     * <pre>
     *CanalModelPacket中包含CanalParametetPacket
     * </pre>
     *
     * <code>optional .CanalParameterMessage canalParameterMessage = 5;</code>
     */
    boolean hasCanalParameterMessage();
    /**
     * <pre>
     *CanalModelPacket中包含CanalParametetPacket
     * </pre>
     *
     * <code>optional .CanalParameterMessage canalParameterMessage = 5;</code>
     */
    com.alibaba.otter.canal.instance.manager.protocol.CanalParameterPacket.CanalParameterMessage getCanalParameterMessage();
    /**
     * <pre>
     *CanalModelPacket中包含CanalParametetPacket
     * </pre>
     *
     * <code>optional .CanalParameterMessage canalParameterMessage = 5;</code>
     */
    com.alibaba.otter.canal.instance.manager.protocol.CanalParameterPacket.CanalParameterMessageOrBuilder getCanalParameterMessageOrBuilder();

    /**
     * <pre>
     *两个时间全部用字符串来表示
     * </pre>
     *
     * <code>optional string gmtCreate = 6;</code>
     */
    java.lang.String getGmtCreate();
    /**
     * <pre>
     *两个时间全部用字符串来表示
     * </pre>
     *
     * <code>optional string gmtCreate = 6;</code>
     */
    com.google.protobuf.ByteString
        getGmtCreateBytes();

    /**
     * <code>optional string gmtModified = 7;</code>
     */
    java.lang.String getGmtModified();
    /**
     * <code>optional string gmtModified = 7;</code>
     */
    com.google.protobuf.ByteString
        getGmtModifiedBytes();
  }
  /**
   * Protobuf type {@code CanalModelMessage}
   */
  public  static final class CanalModelMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:CanalModelMessage)
      CanalModelMessageOrBuilder {
    // Use CanalModelMessage.newBuilder() to construct.
    private CanalModelMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CanalModelMessage() {
      id_ = 0L;
      name_ = "";
      desc_ = "";
      status_ = 0;
      gmtCreate_ = "";
      gmtModified_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private CanalModelMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              id_ = input.readInt64();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              desc_ = s;
              break;
            }
            case 32: {
              int rawValue = input.readEnum();

              status_ = rawValue;
              break;
            }
            case 42: {
              com.alibaba.otter.canal.instance.manager.protocol.CanalParameterPacket.CanalParameterMessage.Builder subBuilder = null;
              if (canalParameterMessage_ != null) {
                subBuilder = canalParameterMessage_.toBuilder();
              }
              canalParameterMessage_ = input.readMessage(com.alibaba.otter.canal.instance.manager.protocol.CanalParameterPacket.CanalParameterMessage.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(canalParameterMessage_);
                canalParameterMessage_ = subBuilder.buildPartial();
              }

              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              gmtCreate_ = s;
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              gmtModified_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.alibaba.otter.canal.instance.manager.protocol.CanalModelPacket.internal_static_CanalModelMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.alibaba.otter.canal.instance.manager.protocol.CanalModelPacket.internal_static_CanalModelMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.alibaba.otter.canal.instance.manager.protocol.CanalModelPacket.CanalModelMessage.class, com.alibaba.otter.canal.instance.manager.protocol.CanalModelPacket.CanalModelMessage.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>optional int64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>optional string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>optional string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DESC_FIELD_NUMBER = 3;
    private volatile java.lang.Object desc_;
    /**
     * <code>optional string desc = 3;</code>
     */
    public java.lang.String getDesc() {
      java.lang.Object ref = desc_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        desc_ = s;
        return s;
      }
    }
    /**
     * <code>optional string desc = 3;</code>
     */
    public com.google.protobuf.ByteString
        getDescBytes() {
      java.lang.Object ref = desc_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        desc_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STATUS_FIELD_NUMBER = 4;
    private int status_;
    /**
     * <code>optional .CanalStatusMessage status = 4;</code>
     */
    public int getStatusValue() {
      return status_;
    }
    /**
     * <code>optional .CanalStatusMessage status = 4;</code>
     */
    public com.alibaba.otter.canal.instance.manager.protocol.CanalModelPacket.CanalStatusMessage getStatus() {
      com.alibaba.otter.canal.instance.manager.protocol.CanalModelPacket.CanalStatusMessage result = com.alibaba.otter.canal.instance.manager.protocol.CanalModelPacket.CanalStatusMessage.valueOf(status_);
      return result == null ? com.alibaba.otter.canal.instance.manager.protocol.CanalModelPacket.CanalStatusMessage.UNRECOGNIZED : result;
    }

    public static final int CANALPARAMETERMESSAGE_FIELD_NUMBER = 5;
    private com.alibaba.otter.canal.instance.manager.protocol.CanalParameterPacket.CanalParameterMessage canalParameterMessage_;
    /**
     * <pre>
     *CanalModelPacket中包含CanalParametetPacket
     * </pre>
     *
     * <code>optional .CanalParameterMessage canalParameterMessage = 5;</code>
     */
    public boolean hasCanalParameterMessage() {
      return canalParameterMessage_ != null;
    }
    /**
     * <pre>
     *CanalModelPacket中包含CanalParametetPacket
     * </pre>
     *
     * <code>optional .CanalParameterMessage canalParameterMessage = 5;</code>
     */
    public com.alibaba.otter.canal.instance.manager.protocol.CanalParameterPacket.CanalParameterMessage getCanalParameterMessage() {
      return canalParameterMessage_ == null ? com.alibaba.otter.canal.instance.manager.protocol.CanalParameterPacket.CanalParameterMessage.getDefaultInstance() : canalParameterMessage_;
    }
    /**
     * <pre>
     *CanalModelPacket中包含CanalParametetPacket
     * </pre>
     *
     * <code>optional .CanalParameterMessage canalParameterMessage = 5;</code>
     */
    public com.alibaba.otter.canal.instance.manager.protocol.CanalParameterPacket.CanalParameterMessageOrBuilder getCanalParameterMessageOrBuilder() {
      return getCanalParameterMessage();
    }

    public static final int GMTCREATE_FIELD_NUMBER = 6;
    private volatile java.lang.Object gmtCreate_;
    /**
     * <pre>
     *两个时间全部用字符串来表示
     * </pre>
     *
     * <code>optional string gmtCreate = 6;</code>
     */
    public java.lang.String getGmtCreate() {
      java.lang.Object ref = gmtCreate_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        gmtCreate_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *两个时间全部用字符串来表示
     * </pre>
     *
     * <code>optional string gmtCreate = 6;</code>
     */
    public com.google.protobuf.ByteString
        getGmtCreateBytes() {
      java.lang.Object ref = gmtCreate_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        gmtCreate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GMTMODIFIED_FIELD_NUMBER = 7;
    private volatile java.lang.Object gmtModified_;
    /**
     * <code>optional string gmtModified = 7;</code>
     */
    public java.lang.String getGmtModified() {
      java.lang.Object ref = gmtModified_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        gmtModified_ = s;
        return s;
      }
    }
    /**
     * <code>optional string gmtModified = 7;</code>
     */
    public com.google.protobuf.ByteString
        getGmtModifiedBytes() {
      java.lang.Object ref = gmtModified_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        gmtModified_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0L) {
        output.writeInt64(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (!getDescBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, desc_);
      }
      if (status_ != com.alibaba.otter.canal.instance.manager.protocol.CanalModelPacket.CanalStatusMessage.START.getNumber()) {
        output.writeEnum(4, status_);
      }
      if (canalParameterMessage_ != null) {
        output.writeMessage(5, getCanalParameterMessage());
      }
      if (!getGmtCreateBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, gmtCreate_);
      }
      if (!getGmtModifiedBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, gmtModified_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (!getDescBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, desc_);
      }
      if (status_ != com.alibaba.otter.canal.instance.manager.protocol.CanalModelPacket.CanalStatusMessage.START.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, status_);
      }
      if (canalParameterMessage_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getCanalParameterMessage());
      }
      if (!getGmtCreateBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, gmtCreate_);
      }
      if (!getGmtModifiedBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, gmtModified_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.alibaba.otter.canal.instance.manager.protocol.CanalModelPacket.CanalModelMessage)) {
        return super.equals(obj);
      }
      com.alibaba.otter.canal.instance.manager.protocol.CanalModelPacket.CanalModelMessage other = (com.alibaba.otter.canal.instance.manager.protocol.CanalModelPacket.CanalModelMessage) obj;

      boolean result = true;
      result = result && (getId()
          == other.getId());
      result = result && getName()
          .equals(other.getName());
      result = result && getDesc()
          .equals(other.getDesc());
      result = result && status_ == other.status_;
      result = result && (hasCanalParameterMessage() == other.hasCanalParameterMessage());
      if (hasCanalParameterMessage()) {
        result = result && getCanalParameterMessage()
            .equals(other.getCanalParameterMessage());
      }
      result = result && getGmtCreate()
          .equals(other.getGmtCreate());
      result = result && getGmtModified()
          .equals(other.getGmtModified());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + DESC_FIELD_NUMBER;
      hash = (53 * hash) + getDesc().hashCode();
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + status_;
      if (hasCanalParameterMessage()) {
        hash = (37 * hash) + CANALPARAMETERMESSAGE_FIELD_NUMBER;
        hash = (53 * hash) + getCanalParameterMessage().hashCode();
      }
      hash = (37 * hash) + GMTCREATE_FIELD_NUMBER;
      hash = (53 * hash) + getGmtCreate().hashCode();
      hash = (37 * hash) + GMTMODIFIED_FIELD_NUMBER;
      hash = (53 * hash) + getGmtModified().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.alibaba.otter.canal.instance.manager.protocol.CanalModelPacket.CanalModelMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.alibaba.otter.canal.instance.manager.protocol.CanalModelPacket.CanalModelMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.alibaba.otter.canal.instance.manager.protocol.CanalModelPacket.CanalModelMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.alibaba.otter.canal.instance.manager.protocol.CanalModelPacket.CanalModelMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.alibaba.otter.canal.instance.manager.protocol.CanalModelPacket.CanalModelMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.alibaba.otter.canal.instance.manager.protocol.CanalModelPacket.CanalModelMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.alibaba.otter.canal.instance.manager.protocol.CanalModelPacket.CanalModelMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.alibaba.otter.canal.instance.manager.protocol.CanalModelPacket.CanalModelMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.alibaba.otter.canal.instance.manager.protocol.CanalModelPacket.CanalModelMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.alibaba.otter.canal.instance.manager.protocol.CanalModelPacket.CanalModelMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.alibaba.otter.canal.instance.manager.protocol.CanalModelPacket.CanalModelMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CanalModelMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CanalModelMessage)
        com.alibaba.otter.canal.instance.manager.protocol.CanalModelPacket.CanalModelMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.alibaba.otter.canal.instance.manager.protocol.CanalModelPacket.internal_static_CanalModelMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.alibaba.otter.canal.instance.manager.protocol.CanalModelPacket.internal_static_CanalModelMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.alibaba.otter.canal.instance.manager.protocol.CanalModelPacket.CanalModelMessage.class, com.alibaba.otter.canal.instance.manager.protocol.CanalModelPacket.CanalModelMessage.Builder.class);
      }

      // Construct using com.alibaba.otter.canal.instance.manager.protocol.CanalModelPacket.CanalModelMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = 0L;

        name_ = "";

        desc_ = "";

        status_ = 0;

        if (canalParameterMessageBuilder_ == null) {
          canalParameterMessage_ = null;
        } else {
          canalParameterMessage_ = null;
          canalParameterMessageBuilder_ = null;
        }
        gmtCreate_ = "";

        gmtModified_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.alibaba.otter.canal.instance.manager.protocol.CanalModelPacket.internal_static_CanalModelMessage_descriptor;
      }

      public com.alibaba.otter.canal.instance.manager.protocol.CanalModelPacket.CanalModelMessage getDefaultInstanceForType() {
        return com.alibaba.otter.canal.instance.manager.protocol.CanalModelPacket.CanalModelMessage.getDefaultInstance();
      }

      public com.alibaba.otter.canal.instance.manager.protocol.CanalModelPacket.CanalModelMessage build() {
        com.alibaba.otter.canal.instance.manager.protocol.CanalModelPacket.CanalModelMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.alibaba.otter.canal.instance.manager.protocol.CanalModelPacket.CanalModelMessage buildPartial() {
        com.alibaba.otter.canal.instance.manager.protocol.CanalModelPacket.CanalModelMessage result = new com.alibaba.otter.canal.instance.manager.protocol.CanalModelPacket.CanalModelMessage(this);
        result.id_ = id_;
        result.name_ = name_;
        result.desc_ = desc_;
        result.status_ = status_;
        if (canalParameterMessageBuilder_ == null) {
          result.canalParameterMessage_ = canalParameterMessage_;
        } else {
          result.canalParameterMessage_ = canalParameterMessageBuilder_.build();
        }
        result.gmtCreate_ = gmtCreate_;
        result.gmtModified_ = gmtModified_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.alibaba.otter.canal.instance.manager.protocol.CanalModelPacket.CanalModelMessage) {
          return mergeFrom((com.alibaba.otter.canal.instance.manager.protocol.CanalModelPacket.CanalModelMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.alibaba.otter.canal.instance.manager.protocol.CanalModelPacket.CanalModelMessage other) {
        if (other == com.alibaba.otter.canal.instance.manager.protocol.CanalModelPacket.CanalModelMessage.getDefaultInstance()) return this;
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (!other.getDesc().isEmpty()) {
          desc_ = other.desc_;
          onChanged();
        }
        if (other.status_ != 0) {
          setStatusValue(other.getStatusValue());
        }
        if (other.hasCanalParameterMessage()) {
          mergeCanalParameterMessage(other.getCanalParameterMessage());
        }
        if (!other.getGmtCreate().isEmpty()) {
          gmtCreate_ = other.gmtCreate_;
          onChanged();
        }
        if (!other.getGmtModified().isEmpty()) {
          gmtModified_ = other.gmtModified_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.alibaba.otter.canal.instance.manager.protocol.CanalModelPacket.CanalModelMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.alibaba.otter.canal.instance.manager.protocol.CanalModelPacket.CanalModelMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long id_ ;
      /**
       * <code>optional int64 id = 1;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>optional int64 id = 1;</code>
       */
      public Builder setId(long value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object desc_ = "";
      /**
       * <code>optional string desc = 3;</code>
       */
      public java.lang.String getDesc() {
        java.lang.Object ref = desc_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          desc_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string desc = 3;</code>
       */
      public com.google.protobuf.ByteString
          getDescBytes() {
        java.lang.Object ref = desc_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          desc_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string desc = 3;</code>
       */
      public Builder setDesc(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        desc_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string desc = 3;</code>
       */
      public Builder clearDesc() {
        
        desc_ = getDefaultInstance().getDesc();
        onChanged();
        return this;
      }
      /**
       * <code>optional string desc = 3;</code>
       */
      public Builder setDescBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        desc_ = value;
        onChanged();
        return this;
      }

      private int status_ = 0;
      /**
       * <code>optional .CanalStatusMessage status = 4;</code>
       */
      public int getStatusValue() {
        return status_;
      }
      /**
       * <code>optional .CanalStatusMessage status = 4;</code>
       */
      public Builder setStatusValue(int value) {
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .CanalStatusMessage status = 4;</code>
       */
      public com.alibaba.otter.canal.instance.manager.protocol.CanalModelPacket.CanalStatusMessage getStatus() {
        com.alibaba.otter.canal.instance.manager.protocol.CanalModelPacket.CanalStatusMessage result = com.alibaba.otter.canal.instance.manager.protocol.CanalModelPacket.CanalStatusMessage.valueOf(status_);
        return result == null ? com.alibaba.otter.canal.instance.manager.protocol.CanalModelPacket.CanalStatusMessage.UNRECOGNIZED : result;
      }
      /**
       * <code>optional .CanalStatusMessage status = 4;</code>
       */
      public Builder setStatus(com.alibaba.otter.canal.instance.manager.protocol.CanalModelPacket.CanalStatusMessage value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        status_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .CanalStatusMessage status = 4;</code>
       */
      public Builder clearStatus() {
        
        status_ = 0;
        onChanged();
        return this;
      }

      private com.alibaba.otter.canal.instance.manager.protocol.CanalParameterPacket.CanalParameterMessage canalParameterMessage_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.alibaba.otter.canal.instance.manager.protocol.CanalParameterPacket.CanalParameterMessage, com.alibaba.otter.canal.instance.manager.protocol.CanalParameterPacket.CanalParameterMessage.Builder, com.alibaba.otter.canal.instance.manager.protocol.CanalParameterPacket.CanalParameterMessageOrBuilder> canalParameterMessageBuilder_;
      /**
       * <pre>
       *CanalModelPacket中包含CanalParametetPacket
       * </pre>
       *
       * <code>optional .CanalParameterMessage canalParameterMessage = 5;</code>
       */
      public boolean hasCanalParameterMessage() {
        return canalParameterMessageBuilder_ != null || canalParameterMessage_ != null;
      }
      /**
       * <pre>
       *CanalModelPacket中包含CanalParametetPacket
       * </pre>
       *
       * <code>optional .CanalParameterMessage canalParameterMessage = 5;</code>
       */
      public com.alibaba.otter.canal.instance.manager.protocol.CanalParameterPacket.CanalParameterMessage getCanalParameterMessage() {
        if (canalParameterMessageBuilder_ == null) {
          return canalParameterMessage_ == null ? com.alibaba.otter.canal.instance.manager.protocol.CanalParameterPacket.CanalParameterMessage.getDefaultInstance() : canalParameterMessage_;
        } else {
          return canalParameterMessageBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       *CanalModelPacket中包含CanalParametetPacket
       * </pre>
       *
       * <code>optional .CanalParameterMessage canalParameterMessage = 5;</code>
       */
      public Builder setCanalParameterMessage(com.alibaba.otter.canal.instance.manager.protocol.CanalParameterPacket.CanalParameterMessage value) {
        if (canalParameterMessageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          canalParameterMessage_ = value;
          onChanged();
        } else {
          canalParameterMessageBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       *CanalModelPacket中包含CanalParametetPacket
       * </pre>
       *
       * <code>optional .CanalParameterMessage canalParameterMessage = 5;</code>
       */
      public Builder setCanalParameterMessage(
          com.alibaba.otter.canal.instance.manager.protocol.CanalParameterPacket.CanalParameterMessage.Builder builderForValue) {
        if (canalParameterMessageBuilder_ == null) {
          canalParameterMessage_ = builderForValue.build();
          onChanged();
        } else {
          canalParameterMessageBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       *CanalModelPacket中包含CanalParametetPacket
       * </pre>
       *
       * <code>optional .CanalParameterMessage canalParameterMessage = 5;</code>
       */
      public Builder mergeCanalParameterMessage(com.alibaba.otter.canal.instance.manager.protocol.CanalParameterPacket.CanalParameterMessage value) {
        if (canalParameterMessageBuilder_ == null) {
          if (canalParameterMessage_ != null) {
            canalParameterMessage_ =
              com.alibaba.otter.canal.instance.manager.protocol.CanalParameterPacket.CanalParameterMessage.newBuilder(canalParameterMessage_).mergeFrom(value).buildPartial();
          } else {
            canalParameterMessage_ = value;
          }
          onChanged();
        } else {
          canalParameterMessageBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       *CanalModelPacket中包含CanalParametetPacket
       * </pre>
       *
       * <code>optional .CanalParameterMessage canalParameterMessage = 5;</code>
       */
      public Builder clearCanalParameterMessage() {
        if (canalParameterMessageBuilder_ == null) {
          canalParameterMessage_ = null;
          onChanged();
        } else {
          canalParameterMessage_ = null;
          canalParameterMessageBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       *CanalModelPacket中包含CanalParametetPacket
       * </pre>
       *
       * <code>optional .CanalParameterMessage canalParameterMessage = 5;</code>
       */
      public com.alibaba.otter.canal.instance.manager.protocol.CanalParameterPacket.CanalParameterMessage.Builder getCanalParameterMessageBuilder() {
        
        onChanged();
        return getCanalParameterMessageFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       *CanalModelPacket中包含CanalParametetPacket
       * </pre>
       *
       * <code>optional .CanalParameterMessage canalParameterMessage = 5;</code>
       */
      public com.alibaba.otter.canal.instance.manager.protocol.CanalParameterPacket.CanalParameterMessageOrBuilder getCanalParameterMessageOrBuilder() {
        if (canalParameterMessageBuilder_ != null) {
          return canalParameterMessageBuilder_.getMessageOrBuilder();
        } else {
          return canalParameterMessage_ == null ?
              com.alibaba.otter.canal.instance.manager.protocol.CanalParameterPacket.CanalParameterMessage.getDefaultInstance() : canalParameterMessage_;
        }
      }
      /**
       * <pre>
       *CanalModelPacket中包含CanalParametetPacket
       * </pre>
       *
       * <code>optional .CanalParameterMessage canalParameterMessage = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.alibaba.otter.canal.instance.manager.protocol.CanalParameterPacket.CanalParameterMessage, com.alibaba.otter.canal.instance.manager.protocol.CanalParameterPacket.CanalParameterMessage.Builder, com.alibaba.otter.canal.instance.manager.protocol.CanalParameterPacket.CanalParameterMessageOrBuilder> 
          getCanalParameterMessageFieldBuilder() {
        if (canalParameterMessageBuilder_ == null) {
          canalParameterMessageBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.alibaba.otter.canal.instance.manager.protocol.CanalParameterPacket.CanalParameterMessage, com.alibaba.otter.canal.instance.manager.protocol.CanalParameterPacket.CanalParameterMessage.Builder, com.alibaba.otter.canal.instance.manager.protocol.CanalParameterPacket.CanalParameterMessageOrBuilder>(
                  getCanalParameterMessage(),
                  getParentForChildren(),
                  isClean());
          canalParameterMessage_ = null;
        }
        return canalParameterMessageBuilder_;
      }

      private java.lang.Object gmtCreate_ = "";
      /**
       * <pre>
       *两个时间全部用字符串来表示
       * </pre>
       *
       * <code>optional string gmtCreate = 6;</code>
       */
      public java.lang.String getGmtCreate() {
        java.lang.Object ref = gmtCreate_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          gmtCreate_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *两个时间全部用字符串来表示
       * </pre>
       *
       * <code>optional string gmtCreate = 6;</code>
       */
      public com.google.protobuf.ByteString
          getGmtCreateBytes() {
        java.lang.Object ref = gmtCreate_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          gmtCreate_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *两个时间全部用字符串来表示
       * </pre>
       *
       * <code>optional string gmtCreate = 6;</code>
       */
      public Builder setGmtCreate(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        gmtCreate_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *两个时间全部用字符串来表示
       * </pre>
       *
       * <code>optional string gmtCreate = 6;</code>
       */
      public Builder clearGmtCreate() {
        
        gmtCreate_ = getDefaultInstance().getGmtCreate();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *两个时间全部用字符串来表示
       * </pre>
       *
       * <code>optional string gmtCreate = 6;</code>
       */
      public Builder setGmtCreateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        gmtCreate_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object gmtModified_ = "";
      /**
       * <code>optional string gmtModified = 7;</code>
       */
      public java.lang.String getGmtModified() {
        java.lang.Object ref = gmtModified_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          gmtModified_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string gmtModified = 7;</code>
       */
      public com.google.protobuf.ByteString
          getGmtModifiedBytes() {
        java.lang.Object ref = gmtModified_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          gmtModified_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string gmtModified = 7;</code>
       */
      public Builder setGmtModified(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        gmtModified_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string gmtModified = 7;</code>
       */
      public Builder clearGmtModified() {
        
        gmtModified_ = getDefaultInstance().getGmtModified();
        onChanged();
        return this;
      }
      /**
       * <code>optional string gmtModified = 7;</code>
       */
      public Builder setGmtModifiedBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        gmtModified_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:CanalModelMessage)
    }

    // @@protoc_insertion_point(class_scope:CanalModelMessage)
    private static final com.alibaba.otter.canal.instance.manager.protocol.CanalModelPacket.CanalModelMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.alibaba.otter.canal.instance.manager.protocol.CanalModelPacket.CanalModelMessage();
    }

    public static com.alibaba.otter.canal.instance.manager.protocol.CanalModelPacket.CanalModelMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CanalModelMessage>
        PARSER = new com.google.protobuf.AbstractParser<CanalModelMessage>() {
      public CanalModelMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new CanalModelMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CanalModelMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CanalModelMessage> getParserForType() {
      return PARSER;
    }

    public com.alibaba.otter.canal.instance.manager.protocol.CanalModelPacket.CanalModelMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CanalModelMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CanalModelMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030CanalModelProtocol.proto\032\034CanalParamet" +
      "erProtocol.proto\"\277\001\n\021CanalModelMessage\022\n" +
      "\n\002id\030\001 \001(\003\022\014\n\004name\030\002 \001(\t\022\014\n\004desc\030\003 \001(\t\022#" +
      "\n\006status\030\004 \001(\0162\023.CanalStatusMessage\0225\n\025c" +
      "analParameterMessage\030\005 \001(\0132\026.CanalParame" +
      "terMessage\022\021\n\tgmtCreate\030\006 \001(\t\022\023\n\013gmtModi" +
      "fied\030\007 \001(\t*)\n\022CanalStatusMessage\022\t\n\005STAR" +
      "T\020\000\022\010\n\004STOP\020\001BG\n1com.alibaba.otter.canal" +
      ".instance.manager.protocolB\020CanalModelPa" +
      "cketH\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.alibaba.otter.canal.instance.manager.protocol.CanalParameterPacket.getDescriptor(),
        }, assigner);
    internal_static_CanalModelMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CanalModelMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CanalModelMessage_descriptor,
        new java.lang.String[] { "Id", "Name", "Desc", "Status", "CanalParameterMessage", "GmtCreate", "GmtModified", });
    com.alibaba.otter.canal.instance.manager.protocol.CanalParameterPacket.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
